import image1 from "@/assets/images/img_1.png";
import image2 from "@/assets/images/img_2.png";
import image3 from "@/assets/images/img_3.png";

export const blogArticles = [
  {
    id: "0",
    icon: image1,
    info: "22 June 2022",
    text: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas. Quis autem vel eum iure...",
    heading: "ISO 13485 compliance of medical devices",
    tags: ["App", "Media"],
    views: 483,
    author: "smb",
  },
  {
    id: "1",
    icon: image2,
    info: "22 June 2022",
    text: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas. Quis autem vel eum iure...",
    heading: "IBusiness analysis helps you  in finance",
    tags: ["Management", "CMR"],
    views: 482,
    author: "smb",
  },
  {
    id: "2",
    icon: image3,
    info: "22 June 2022",
    text: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas. Quis autem vel eum iure...",
    heading: "5 web portal examples your business can learn from",
    tags: ["Future", "CIO"],
    views: 481,
    author: "smb",
  },
  {
    id: "3",
    icon: image3,
    info: "24 June 2022",
    text: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas. Quis autem vel eum iure...",
    heading: "5 web portal examples your business can learn from",
    tags: ["Big data", "Startup"],
    views: 479,
    author: "smb",
  },
  {
    id: "4",
    icon: image2,
    info: "22 June 2022",
    text: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas. Quis autem vel eum iure...",
    heading: "IBusiness analysis helps you  in finance",
    tags: ["Team", "Data", "Proxy"],
    views: 476,
    author: "smb",
  },
  {
    id: "5",
    icon: image1,
    info: "22 June 2022",
    text: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas. Quis autem vel eum iure...",
    heading: "ISO 13485 compliance of medical devices",
    tags: ["Data analytics", "Information security"],
    views: 474,
    author: "smb",
  },
];
