name: 'Lint checker'

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Action Lint
        uses: panda0603/lint-action@1.6.3

